(custom-set-faces
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#C071E1"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#8371E1"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#719BE1"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#71DDE1"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#71E19B"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#8EE171"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#D8E171"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#E1A071"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#E17471"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "orange red"))))
 )
